# Server
server.port=${SERVER_PORT:8080}

# Datasource
spring.datasource.url=jdbc:sqlserver://localhost:${SQL_PORT:1434};databaseName=${DB_NAME:mydb};trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=${SA_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect